{
 "title": "Jitsi jvb metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Conference sizes",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "\nconference_sizes_bucket{app=\"jitsi\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nconferences{app=\"jitsi\"}",
     "legendFormat": "Bridge: {{ jvb_instance }}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nparticipants{app=\"jitsi\"}",
     "legendFormat": "Bridge: {{ jvb_instance }}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "\nbit_rate_download{app=\"jitsi\"}",
     "legendFormat": "Bridge: {{ jvb_instance }}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "\nbit_rate_upload{app=\"jitsi\"}",
     "legendFormat": "Bridge: {{ jvb_instance }}"
    }
   ]
  }
 ]
}