{
 "title": "Jitsi Meet",
 "description": "Dashboard for stats gathered by 3rd party exporter karrieretutor/jitsi-prom-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(go_info{job = \"jitsi\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Conferences",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "participants{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "largest_conference{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "RX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_received{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Conference seconds",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conference_seconds{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Failed Conferences",
   "type": "singlestat",
   "description": "The total number of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_failed_conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "No payload channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_no_payload_channels{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cpu_usage{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "used_memory{instance = \"$instance\"}",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "threads{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_channels{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "TX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_sent{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conferences_completed{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Partially Failed Conferences",
   "type": "singlestat",
   "description": "The total number of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_partially_failed_conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "No transport channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_no_transport_channels{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance = \"$instance\"} * 1000",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "conferences{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "participants{instance = \"$instance\"}",
     "legendFormat": "people"
    }
   ]
  },
  {
   "title": "Video streams",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "videostreams{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Channels created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(total_channels{instance = \"$instance\"}[1h])",
     "legendFormat": "channels"
    }
   ]
  },
  {
   "title": "Audio channels",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "audiochannels{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Video channels",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "videochannels{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "RTT aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rtt_aggregate{instance = \"$instance\"}",
     "legendFormat": "RTT"
    }
   ]
  },
  {
   "title": "Jitter aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitter_aggregate{instance = \"$instance\"}",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Bitrate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "bit_rate_upload{instance = \"$instance\"}",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Packet rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packet_rate_upload{instance = \"$instance\"}",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Loss rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "loss_rate_upload{instance = \"$instance\"}",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Datachannel messages received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_data_channel_messages_received{instance = \"$instance\"}[5m])",
     "legendFormat": "msg"
    }
   ]
  },
  {
   "title": "Bitrate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "bit_rate_download{instance = \"$instance\"}",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Packet rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packet_rate_download{instance = \"$instance\"}",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Loss rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "loss_rate_download{instance = \"$instance\"}",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Datachannel messages sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_data_channel_messages_sent{instance = \"$instance\"}[5m])",
     "legendFormat": "msg"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_sent{instance = \"$instance\"}[1h])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_received{instance = \"$instance\"}[1h])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Loss-controlled participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_controlled_participant_seconds{instance = \"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Loss-degraded participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_degraded_participant_seconds{instance = \"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Loss-limited participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_limited_participant_seconds{instance = \"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Conference sizes combined",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (le) (conference_sizes_combined_bucket{job = \"jitsi\"})",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conference sizes",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (le) (conference_sizes_bucket{job = \"jitsi\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Exporter CPU usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance = \"$instance\"}[5m])",
       "legendFormat": "{{ CPU }}"
      }
     ]
    }
   ]
  }
 ]
}